Migration specifications du contenu
canada-ca/systeme-conception pull request #126
Opened 2023-03-28 13:23 UTC by prycrane

Pull request for moving Content and Information Architecture Specification section from AEM to design-system.

design-system: https://github.com/canada-ca/design-system/pull/200

(File numbers may not match English numbers for this round.  Will get repaired as the migration continues.)

2023-04-04 13:47 UTC, prycrane commented
Perhaps we can meet this afternoon and flip this into production.

2023-04-17 13:28 UTC, delisma requested changes

2023-04-17 13:28 UTC, delisma commented on architecture/utilisation-concept-canadaca.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
Use of variable has to be tested.

2023-04-17 13:28 UTC, delisma commented on architecture/utilisation-concept-canadaca.md
> +<p class="gc-byline"><strong>De : <a href="/fr/secretariat-conseil-tresor.html">Secrétariat du Conseil du Trésor du Canada</a></strong></p>
```suggestion
<p class="gc-byline"><strong>De : <a href="https://www.canada.ca/fr/secretariat-conseil-tresor.html">Secrétariat du Conseil du Trésor du Canada</a></strong></p>
```

2023-04-17 13:28 UTC, delisma commented on configurations-conception-communes/widget-medias-sociaux.html
Revert changes to remove this file from the PR

2023-04-17 13:28 UTC, delisma commented on modeles-obligatoire/pages-publics-cibles.html
Revert changes to remove page from PR

2023-04-17 13:28 UTC, delisma commented on modeles-obligatoire/pages-theme-backup.html
Should be deleted. Will file issue in the future.

2023-04-17 13:28 UTC, delisma commented on modeles-obligatoire/theme-sujet-draft.html
Should be deleted. Will file issue in the future

2023-04-17 13:28 UTC, delisma commented on modeles-recommandes/pages-description-programme.html
Revert changes to remove page from PR

2023-04-17 13:28 UTC, delisma commented on modeles-recommandes/pages-directives-lois.html
Revert changes to remove page from PR

2023-04-17 13:28 UTC, delisma commented on modeles-recommandes/pages-lancement-service.html
Revert changes to remove page from PR

2023-04-17 13:28 UTC, delisma commented on test.html
Revert changes to remove page from PR

2023-05-02 12:17 UTC, prycrane commented on README.md
> +Afin de passer à un système de conception plus souple, le plan consiste à «découpler» les spécifications détaillées des modèles des «documents de politique» officiels - la [spécification d'architectu
Done

2023-05-02 12:24 UTC, prycrane commented on architecture/utilisation-concept-canadaca.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
Can you verify, @delisma ?

2023-05-02 12:29 UTC, prycrane commented on configurations-conception-communes/widget-medias-sociaux.html
Done

2023-05-02 12:34 UTC, prycrane commented on modeles-obligatoire/pages-publics-cibles.html
Done

2023-05-02 12:40 UTC, prycrane commented on modeles-obligatoire/theme-sujet-draft.html
https://github.com/canada-ca/systeme-conception/pull/137

2023-05-02 12:44 UTC, prycrane commented on modeles-recommandes/pages-description-programme.html
done

2023-05-02 12:48 UTC, prycrane commented on modeles-recommandes/pages-lancement-service.html
Done

2023-05-03 18:05 UTC, delisma requested changes

2023-05-03 18:05 UTC, delisma commented on architecture/organiser-contenu.md
> +        <img src="/content/dam/tbs-sct/images/government-communications/canada-content-style-guide/conceptual-overview-fra.png" class="img-responsive center-block" alt="Diagramme de l’aperçu conceptu
```suggestion
        <img src="/content/dam/tbs-sct/images/government-communications/canada-content-style-guide/conceptual-overview-fra.png" class="img-responsive center-block" alt="Diagramme de l’aperçu conceptuel de l’architecture de l’information. La version textuelle se trouve ci-dessous&nbsp;:">
```
Change the dam thing.

2023-05-08 15:56 UTC, delisma requested changes
A few couple of changes are still required. Almost there.

2023-05-08 15:56 UTC, delisma commented on architecture/organiser-contenu.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
Still need to remove the quotes in the Frontmatter.

2023-05-08 15:56 UTC, delisma commented on architecture/elements-obligatoires.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
Still need to remove the quotes

2023-05-08 15:56 UTC, delisma commented on architecture/modeles.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
Need to remove the quotes

2023-05-08 15:56 UTC, delisma commented on architecture/utilisation-concept-canadaca.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
Still need to remove quotes

2023-05-08 15:56 UTC, delisma requested changes
A few couple of changes are still required. Almost there.
The images are not included in this PR and we have 22 html files compared to 24 html in the English PR.
We should consider moving the breadcrumbs for the architecture folder into the _config.yml file as a default setting.

2023-05-10 17:31 UTC, prycrane commented on architecture/elements-obligatoires.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
![image](https://github.com/canada-ca/systeme-conception/assets/96494429/240ea6a7-3625-4d91-8f31-0fb9bcd31f8c)
It does not seem to removing quotes.  Alas.

2023-05-10 17:39 UTC, prycrane commented on architecture/organiser-contenu.md
> +        <img src="/content/dam/tbs-sct/images/government-communications/canada-content-style-guide/conceptual-overview-fra.png" class="img-responsive center-block" alt="Diagramme de l’aperçu conceptu
fixed

2023-05-10 18:14 UTC, prycrane commented on architecture/elements-obligatoires.md
> +    link: "{{ site.url }}/architecture/specifications-contenu-architecture-information-canada.html"
I updated the breadcrumb front matter (Including on the English side.)  @delisma - please have a look at upgrading the config file.

2023-05-17 19:44 UTC, delisma approved these changes
LGTM

2023-05-17 19:55 UTC, delisma commented on modeles-obligatoire/pages-publics-cibles.html
This modification wasn't required in English

2023-05-17 20:02 UTC, merged