Create contactez-nous
canada-ca/systeme-conception pull request #135
Opened 2023-04-12 16:33 UTC by delisma

### Alternate language PR
https://github.com/canada-ca/design-system/pull/231

2023-04-12 18:54 UTC, jmealing approved these changes

2023-04-14 20:35 UTC, LPipes4 requested changes

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +Communiquez avec nous pour poser des questions sur la conception de Canada.ca ou pour nous faire part de vos suggestions à ce sujet.
```suggestion
Communiquez avec nous pour poser des questions sur la conception du site Canada.ca ou pour nous faire part de vos suggestions à ce sujet.
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +      <summary>Information sur la confidentialité </summary>
```suggestion
      <summary>La protection des renseignements personnels</summary>
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +      <p class="mrgn-tp-lg">Nous recueillons les informations personnelles que vous soumettez par le biais de ce formulaire de contact en vertu de <i>la Loi sur la gestion des finances publiques</i>,
```suggestion
      <p class="mrgn-tp-lg">Nous recueillons les informations personnelles que vous soumettez au moyen du présent formulaire permettant de communiquer avec nous en vertu de <i>la Loi sur la gestion des finances publiques</i>, afin de pouvoir vous répondre. Les renseignements demandés sont fournis sur une base volontaire. Les renseignements personnels recueillis seront mis à la disposition du personnel du programme chargé de l'administration du site web et seront utilisés et protégés conformément à <i>la Loi sur la protection des renseignements personnels</i> et tel qu’il est indiqué dans le fichier de renseignements personnels POU 914 - Communications publiques. En vertu de <i>la Loi sur la protection des renseignements personnels</i>, qui protège vos renseignements personnels, vous avez le droit de consulter ces renseignements et de demander que des corrections y soient apportées. Si vous avez des questions à propos des présents renseignements sur la protection des renseignements personnels, veuillez communiquer avec le coordinateur/la coordonnatrice de l’accès à l’information et de la protection des renseignements personnels (AIPRP) du SCT. Si la réponse du SCT à vos préoccupations en matière de protection des renseignements personnels ne vous satisfait pas, vous pouvez communiquer avec le Commissariat à la protection de la vie privée.</p>
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +      <p class="mrgn-tp-lg">Nous recueillons les informations personnelles que vous soumettez par le biais de ce formulaire de contact en vertu de <i>la Loi sur la gestion des finances publiques</i>,
Also...should we use cite tags or i tags?

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +      <p>Coordonnateur de l’AIPRP du Secrétariat du Conseil du Trésor du Canada</p>
```suggestion
      <p>Coordonnateur/Coordonnatrice de l’AIPRP du Conseil du Trésor</p>
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +        <li><a href="https://laws-lois.justice.gc.ca/fra/lois/p-21/index.html"><i>Loi sur la protection des renseignements personnels</i></a></li>
should this be i tags or cite tags?

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +      <p>Voulez-vous que nous vous contactions au sujet de vos commentaires&nbsp;?</p>
```suggestion
      <p>Souhaitez-vous que nous communiquions avec vous au sujet de vos commentaires&nbsp;?</p>
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/index.md
> +          ]'>Oui, je suis prêt à fournir mon courriel uniquement à des fins de contact.</li>
```suggestion
          ]'>Oui, je suis à l’aise de fournir mon adresse courriel à des fins de communication seulement.</li>
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/merci.md
> +Nous avons bien reçu votre message. Si vous avez fourni un courriel, un membre de l'équipe vous répondra dans les 5 jours ouvrables.
```suggestion
Nous avons bien reçu votre message. Si vous avez fourni une adresse courriel, un membre de notre équipe vous répondra dans les 5 jours ouvrables.
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/merci.md
> +Nous apprécions vos commentaires et vos questions.
```suggestion
Nous vous remercions de nous avoir transmis vos commentaires et vos questions.
```

2023-04-14 20:35 UTC, LPipes4 commented on contactez-nous/merci.md
> +[Inscrivez-vous à la liste de diffusion du Bureau de la transformation numérique](https://blogue.canada.ca/pages/inscrire.html)
```suggestion
[Inscrivez-vous à la liste d'envoi du Bureau de la transformation numérique](https://blogue.canada.ca/pages/inscrire.html)
```

2023-04-18 13:26 UTC, LPipes4 approved these changes

2023-04-18 13:27 UTC, LPipes4 commented
Just the one change that I missed from the translation. Sujet should be Objet. But this is good to go otherwise. No need for another review.

2023-05-03 18:12 UTC, prycrane requested changes

2023-05-03 18:12 UTC, prycrane commented on contactez-nous/gc-referrer.js
Check referrer

2023-05-11 14:53 UTC, donohuech reviewed
I am just reviewing this as part of the GitHub documentation process so I can take screenshots.

2023-05-13 16:01 UTC, delisma commented on contactez-nous/gc-referrer.js
Fixed typo on line 30&31

2023-05-13 16:10 UTC, delisma commented
@prycrane Ready for review

2023-05-19 15:17 UTC, jmealing approved these changes

2023-05-19 15:17 UTC, merged