Dr. or Doctor
canada-ca/systeme-conception pull request #254
Opened 2023-12-04 18:31 UTC by AnneSophieDumetz

2024-01-10 12:39 UTC, prycrane requested changes

2024-01-10 12:39 UTC, prycrane commented on guide-redaction/index.md
> +  <p>test</p>
This line needs to be removed.

2024-01-18 18:20 UTC, prycrane approved these changes

2024-01-18 19:21 UTC, prycrane approved these changes

2024-01-23 19:20 UTC, donohuech approved these changes

2024-01-23 19:22 UTC, merged