Improving content on Canada.ca
canada-ca/systeme-conception pull request #256
Opened 2023-12-08 12:17 UTC by prycrane

2024-02-19 13:26 UTC, donohuech commented
@prycrane on the English page: https://deploy-preview-394--design-system-canada-ca.netlify.app/partners/ we have the dates for each project but on the French page we don't https://deploy-preview-256--systeme-conception-canada-ca.netlify.app/partenaires/

2024-02-19 14:08 UTC, donohuech requested changes

2024-02-20 14:35 UTC, prycrane commented on partenaires/project-09.md
> +description: "Projet partenaire : Make it easier for Canadian parents to understand and apply for maternity and parental benefits."
Done

2024-02-20 14:43 UTC, prycrane commented on partenaires/project-09.md
> +  <li>iane attend un bébé. Elle veut prendre un congé aussi long que possible. Son partenaire veut également prendre quatre semaines de congé immédiatement après la naissance. Quelle est la durée max
fixed

2024-02-20 14:53 UTC, prycrane commented on partenaires/project-10.md
> +  <li>Services publics et Approvisionnement Canada (SPAC)</li>
Done

2024-02-20 14:54 UTC, prycrane commented on partenaires/project-10.md
> +Vous voulez nommer votre entreprise &laquo;&nbsp;SOMOS &nbsp;&raquo;. Vérifiez s'il est légal ou illégal pour vous de commencer à utiliser ce nom.
done.

2024-02-20 14:54 UTC, prycrane commented on partenaires/project-10.md
> +Vous pensez gagner environ 1 000 $ par mois de votre nouvelle entreprise pendant les six premiers mois. Vérifiez si vous devez facturer la TPS à vos clients.
Done.

2024-02-20 14:55 UTC, prycrane commented on partenaires/project-10.md
> +Votre premier employé commence à travailler le mois prochain. Vérifiez si vous devez appliquer une mesure officielle avant ou peu après avoir émis son premier chèque de paye.
Done.

2024-02-20 15:01 UTC, prycrane commented on partenaires/project-13.md
> +<p>Make it easier for applicants to study for the Canadian citizenship test.</p>
Fixed

2024-02-20 15:04 UTC, prycrane commented on partenaires/project-13.md
> +    Quelles sont les différentes façons d'étudier pour l'examen pour la citoyenneté canadienne?
Fixed

2024-02-20 15:04 UTC, prycrane commented on partenaires/project-13.md
> +    Y aura-t-il des questions pour évaluer vos compétences linguistiques en anglais ou en français dans le cadre de l'examen pour la citoyenneté?
Fixed.

2024-02-20 15:04 UTC, prycrane commented on partenaires/project-13.md
> +    Selon le guide de l'étude sur la citoyenneté, que signifie le mot Inuit?
Fixed

2024-02-20 15:04 UTC, prycrane commented on partenaires/project-13.md
> +    Que devez-vous emporter avec vous lorsque vous allez passer l'examen de citoyenneté?</li>
Fixed

2024-02-20 15:06 UTC, prycrane commented on partenaires/project-14.md
> +  <li>ARediriger les transactions simples vers des options numériques moins coûteuses réduit les coûts de soutien pour l'ARC.</li>
Fixed

2024-02-20 15:07 UTC, prycrane commented on partenaires/project-19.md
> +<p>Make it easier for Canadians to understand notifications about dangerous weather conditions.</p>
Fixed

2024-02-20 15:12 UTC, prycrane commented on partenaires/project-09.md
> +title: "Rendre les prestations de maternité et les prestations parentales de l’assurance-emploi plus faciles à trouver et à comprendre pour les Canadiens et Canadiennes qui prévoient agrandir leur fa
fixed

2024-02-20 15:12 UTC, prycrane commented on partenaires/project-10.md
> +Votre entreprise doit commencer à percevoir la TPS. Vérifier quelle est la première mesure officielle que vous devez appliquer.
Fixed

2024-02-20 17:03 UTC, donohuech approved these changes

2024-02-20 17:04 UTC, merged